/**
 * This file generated by Apso.
 */
import { CustomerModule } from './Customer/Customer.module';
import { ContactModule } from './Contact/Contact.module';
import { DealModule } from './Deal/Deal.module';
import { NoteModule } from './Note/Note.module';
import { ActivityModule } from './Activity/Activity.module';

export default [
  CustomerModule,
  ContactModule,
  DealModule,
  NoteModule,
  ActivityModule,
];
