import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ActivityCreate {
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  contact_id: number;
  @ApiProperty()
  deal_id: number;
  @ApiProperty()
  type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  date: string;
}

export class Activity {
  @ApiProperty()
  id: number;
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  contact_id: number;
  @ApiProperty()
  deal_id: number;
  @ApiProperty()
  type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  date: string;
}
