import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class NoteCreate {
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  contact_id: number;
  @ApiProperty()
  deal_id: number;
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_at: Date;
}

export class Note {
  @ApiProperty()
  id: number;
  @ApiProperty()
  customer_id: number;
  @ApiProperty()
  contact_id: number;
  @ApiProperty()
  deal_id: number;
  @ApiProperty()
  content: string;
  @ApiProperty()
  created_at: Date;
}
